### ISSUE TITLE
gulp dist fails

### ISSUE THREAD

**Issue by slimandslam** [jiemakel/snapper#8]
Ubuntu 14.04 with nodejs v4.2.3  (fails completely with CentOS 7 so I switched to Ubuntu)

$ gulp dist
[15:34:43] Requiring external module livescript
[15:34:44] Using gulpfile ~/Desktop/snapper-master/gulpfile.ls
[15:34:44] Starting 'dist'...
[15:34:44] Starting 'build'...
[15:34:44] Starting 'clean'...
[15:34:44] Finished 'clean' after 49 ms
[15:34:44] Starting 'wiredep:styles'...
[15:34:44] Starting 'wiredep:scripts'...
[15:34:44] Starting 'templates'...
[15:34:45] Starting 'styles'...
[15:34:45] Starting 'scripts'...
[15:34:46] Finished 'wiredep:styles' after 2.11 s
[15:34:46] Finished 'wiredep:scripts' after 2.1 s
[15:34:46] Starting 'wiredep'...
[15:34:46] Finished 'wiredep' after 6.29 μs
[15:34:47] Finished 'styles' after 1.85 s
[15:34:47] Finished 'templates' after 2.44 s
[15:34:47] Starting 'partials'...
[15:34:47] Finished 'partials' after 83 ms
[15:34:47] Finished 'scripts' after 1.74 s
[15:34:47] Finished 'build' after 2.59 s
[15:34:47] Starting 'dist:partials'...
[15:34:47] Starting 'dist:refimages'...
[15:34:47] Starting 'dist:refs'...
[15:34:47] Starting 'dist:cssimages'...
[15:34:47] Starting 'dist:cssfonts'...
[15:34:47] Starting 'dist:images'...
[15:34:47] Finished 'dist:images' after 40 ms
[15:34:47] Finished 'dist:partials' after 588 ms
[15:34:47] Starting 'dist:html'...
[15:34:48] dist:html(1) .tmp/index.html
[15:34:48] dist:html(1) all files 4.59 kB
[15:34:48] gulp-inject 1 files into index.html.
[15:34:48] gulp-notify: [Error running Gulp] Error: Error: File not found with singular glob: /home/user/Desktop/snapper-master/app/bower_components/yasqe/dist/yasqe.js
    at DestroyableTransform.<anonymous> (/home/user/Desktop/snapper-master/node_modules/gulp-useref/index.js:135:44)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at emitOne (events.js:82:20)
    at Through2.emit (events.js:169:7)
    at OrderedStreams.<anonymous> (/home/user/Desktop/snapper-master/node_modules/gulp-useref/node_modules/vinyl-fs/node_modules/glob-stream/index.js:138:20)
    at emitOne (events.js:77:13)
    at OrderedStreams.emit (events.js:169:7)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at Glob.<anonymous> (/home/user/Desktop/snapper-master/node_modules/gulp-useref/node_modules/vinyl-fs/node_modules/glob-stream/index.js:38:16)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (/home/user/Desktop/snapper-master/node_modules/gulp-useref/node_modules/glob/glob.js:172:8)
    at done (/home/user/Desktop/snapper-master/node_modules/gulp-useref/node_modules/glob/glob.js:159:12)
[15:34:48] dist:html-css(1) .tmp/styles/main-e644c8c2be.css
[15:34:48] dist:html-css(2) .tmp/styles/main-e644c8c2be.css
[15:34:48] dist:html-css(1) all files 1.41 kB
[15:34:48] dist:html-css(2) all files 1.05 kB
[15:34:48] dist:cssfonts(1) app/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.woff
[15:34:48] dist:cssfonts(1) app/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.woff2
[15:34:48] dist:html(2) dist/index.html
[15:34:48] dist:cssfonts(2) dist/styles/icons.woff
[15:34:48] dist:cssfonts(1) app/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.ttf
[15:34:48] dist:html(2) dist/styles/main-e644c8c2be.css
[15:34:48] dist:html(2) all files 2.27 kB
[15:34:48] Finished 'dist:html' after 842 ms
[15:34:48] dist:refs(1) app/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.svg
[15:34:48] dist:cssfonts(1) app/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.svg
[15:34:48] dist:cssfonts(2) dist/styles/icons.woff2
[15:34:48] dist:cssfonts(1) app/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.eot
[15:34:48] dist:cssfonts(2) dist/styles/icons.ttf
[15:34:48] dist:refimages(1) app/bower_components/semantic-ui/dist/themes/default/assets/images/flags.png
[15:34:48] dist:cssimages(1) app/bower_components/semantic-ui/dist/themes/default/assets/images/flags.png
[15:34:48] dist:cssfonts(2) dist/styles/icons.svg
[15:34:48] gulp-notify: [Error running Gulp] Error: spawn /home/user/Desktop/snapper-master/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
[15:34:48] dist:cssimages(2) dist/styles/flags.png
[15:34:48] dist:refs(2) dist/bower_components/semantic-ui/dist/themes/default/assets/fonts/icons.svg
[15:34:48] dist:cssfonts(2) dist/styles/icons.eot
[15:34:48] dist:refimages(1) all files 28.12 kB
[15:34:48] Finished 'dist:refimages' after 1.63 s
[15:34:48] dist:refs(1) all files 313.4 kB
[15:34:48] dist:refs(2) all files 313.4 kB
[15:34:48] Finished 'dist:refs' after 1.22 s
[15:34:48] dist:cssimages(1) all files 28.12 kB
[15:34:48] dist:cssimages(2) all files 28.12 kB
[15:34:48] Finished 'dist:cssimages' after 1.21 s
[15:34:48] dist:cssfonts(1) all files 624.54 kB
[15:34:48] all files 624.54 kB
[15:34:48] dist:cssfonts(2) all files 624.54 kB
[15:34:48] Finished 'dist:cssfonts' after 1.16 s
[15:34:48] Starting 'dist:finished'...
[15:34:48] gulp-notify: [Gulp notification] Distribution finished
[15:34:48] Finished 'dist:finished' after 12 ms
[15:34:48] Finished 'dist' after 4.33 s
$

**Comment by jiemakel** [comment]
Bah, there was a rogue reference to a moved bower dependency in the index file (which I didn't catch because my bower_components also still contained the old version). That has now been fixed.

However, you also seem to have a second problem in your build with optipng not being found. I think this is probably a result of something unrelated to snapper going wrong during your npm install step. Can you please check that and report if you can now get it to build correctly?

**Comment by slimandslam** [comment]
gulp dist still failing on Ubuntu 14.04 with nodejs v4.2.3:

[17:02:49] gulp-notify: [Error running Gulp] Error: spawn /home/user/Desktop/snapper-master/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

npm install is:

$ npm install
npm WARN package.json app@0.0.0 No repository field.
npm WARN package.json app@0.0.0 No license field.
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN optional dep failed, continuing fsevents@1.0.6
-
> bufferutil@1.2.1 install /home/user/Desktop/snapper-master/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild
$

**Comment by jiemakel** [comment]
You did the npm install on a clean directory (i.e. after an rm -rf node_modules/ and possibly even an npm clean cache)?

Because on a clean install, relating to optipng, I see for example:
 > optipng-bin@3.0.4 postinstall /[path]/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js
    ✔ optipng pre-build test passed successfully

**Comment by slimandslam** [comment]
![screen](https://cloud.githubusercontent.com/assets/229575/11844254/59445fcc-a3d3-11e5-94db-70d250b12ca3.jpg)

I started with a fresh download and it seems to be working now. When I do a "gulp serve", I get the attached screen capture. It looks a bit weird (the "i" sitting there and only one line in the editor window(?)

**Comment by slimandslam** [comment]
Using the dist, when you type in to the editor, it generates JS errors. Is that by design?

Example:

vendor-cfbfdced48.js:32:23459
Error: undefined is not an object (evaluating 'e.indexOf')
y@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:32:14392
v@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:32:13875
c@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:32:12712
l@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:32:30212
http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:32:30384
$eval@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:33:5881
$digest@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:33:4402
http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:33:5975
i@http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:31:21359
http://localhost:8888/snapper/scripts/vendor-cfbfdced48.js:31:22809
(anonymous function)vendor-cfbfdced48.js:31:23458
(anonymous function)vendor-cfbfdced48.js:31:9899
lvendor-cfbfdced48.js:31:30295
(anonymous function)vendor-cfbfdced48.js:31:30384
$evalvendor-cfbfdced48.js:32:5881
$digestvendor-cfbfdced48.js:32:4402
(anonymous function)vendor-cfbfdced48.js:32:5975
ivendor-cfbfdced48.js:30:21359
(anonymous function)vendor-cfbfdced48.js:30:22809

**Comment by jiemakel** [comment]
Closing as old.
